name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

steps:
  - uses: actions/checkout@v4
  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.11"
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
  - name: Test with pytest
    run: |
      pip install -r requirements/test.txt
      pytest --junitxml=junit/test-results.xml --cov-report=xml --cov-report=html
